<!DOCTYPE html>
<html>
<head>
    <title>Список заявок</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<body>
<h1 class="text-center">Список заявок</h1>
<table class="table">
    <tr>
        <th>Мастер</th>
        <th>Цех</th>
        <th>Причина вызова</th>
        <th>Принимающий конструктор</th>
        <th>Статус</th>
        <th>Дата создания Заявки</th>
        <th>Дата принятия в обработку</th>
        <th>Действия</th>
    </tr>
    <#list request as req>
        <tr>
            <td>${req.name}</td>
            <td>${req.numberWorkshop}</td>
            <td>${req.description}</td>
            <td>${req.accepted?string("Принята", "Не принята")}</td>
            <td>
                <form action="/updateStatus/${req.id}" method="post" style="display:inline;">
                    <select name="status" class="form-control" onchange="this.form.submit()">
                        <#list statusList as status>
                            <option value="${status}" <#if req.status == status>selected</#if>>${status}</option>
                        </#list>
                    </select>
                </form>
            </td>
            <td>${req.dateStartAccepted?string("dd.MM.yyyy HH:mm")}</td>
            <td>
                <#if req.dateEndAccepted?has_content>
                    ${req.dateEndAccepted?string("dd.MM.yyyy HH:mm")}
                <#else>
                    Не установлена
                </#if>
            </td>
            <td>
                <button type="button" class="btn btn-info" data-toggle="modal"
                        data-target="#infoModal"
                        data-img-src="data:image/png;base64,${req.image}">
                    Посмотреть описание
                </button>
            </td>
        </tr>
    </#list>
</table>
<div class="text-center">
    <a href="/requestForm" class="btn btn-primary">Создать новую заявку</a>
</div>
<!-- Модальное окно -->
<div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="infoModalLabel">Дополнительное описание</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <img id="modalImage" src="" alt="Изображение" style="width: 100%; height: auto;"/>
                <p id="modalDescription"></p> <!-- Здесь будет отображаться описание -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#infoModal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var imgSrc = button.data('img-src');

            var modal = $(this);
            modal.find('#modalImage').attr('src', imgSrc);
        });
    });
</script>
</body>
</html>