<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>Spring Security Example</title>
</head>
<body>
<h1>Welcome!</h1>

<p>Click ADMIN<a href="/admin">here</a> to see a greeting.</p>
<p>Click <a href="/technologistmain">here</a> to see a greeting.</p>
<#--<p>Click <a href="/otkbid">here</a> to see a greeting.</p>-->
<p>Click <a href="/constructormain">here</a> to see a greeting.</p>
</body>
</html>