<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HOME</title>
</head>
<body>
<a href="technologistbid">Создать заявку на вызов технолога</a>
<a href="constructorbid">Создать заявку на вызов конструктора</a>
<a href="otkbid">Создать заявку на вызов ОТК</a>
</body>
</html>