<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TechnologistMain</title>
</head>
<body>
<!--Главное меню технолога с отображением всех заявок-->
<a href="/technologistbid">Создать заявку на вызов технолога</a>
</body>
</html>